Features
vladveterok/todo-api pull request #1
Opened 2020-12-22 20:54 UTC by vladveterok

ToDo API

- [x] Implement all back-end scenarios necessary for fulfilling front-end needs
- [x] Cover with tests
- [x] Generate documentation

Documentation: https://vladveterok.github.io/v1

2020-12-26 12:57 UTC, DaniilYusha requested changes

2020-12-26 12:57 UTC, DaniilYusha commented on Gemfile
> +  gem 'database_cleaner-active_record', '~> 1.8'
why do you use this gem if rspec already has such option? you can set `config.use_transactional_fixtures` to `true` in your `rails_helper` file and this will clear db after each test example

2020-12-26 12:57 UTC, DaniilYusha commented on app/controllers/api/v1/comments_controller.rb
> +        @task = Task.find(params[:task_id])
nit: use `find_by(id: params[:task_id])` please because `find` raises an `ActiveRecord::RecordNotFound` exception if record not found but `find_by` returns `nil`

2020-12-26 12:57 UTC, DaniilYusha commented on app/controllers/api/v1/comments_controller.rb
> +      end
what if pass non-existent id or validations will fail? should you return errors :smile: ?

2020-12-26 12:57 UTC, DaniilYusha commented on app/models/project.rb
> +end
add uniqueness validation for project name please
![Снимок экрана от 2020-12-26 14-16-40](https://user-images.githubusercontent.com/45877757/103151259-1ac0d680-4785-11eb-82b8-c3cefb7c8b3c.png)

2020-12-26 12:57 UTC, DaniilYusha commented on config/routes.rb
> +  post 'refresh', to: 'refresh#create'
nit: why without resource? for example: `resource :signin, only: %[create destroy]`

2020-12-26 12:57 UTC, DaniilYusha commented on db/migrate/20201216202448_create_projects.rb
> +      # t.string :created_by, null: false
remove comment please

2020-12-26 12:57 UTC, DaniilYusha commented on db/seeds.rb
> +project = Project.create(name: 'Seeded project with tasks', user_id: 1)
nit: I think it will be better to replace magic strings with FFaker
also you can use `seedbank` gem (not necessary now but in future :smile: ) to detach creating process of your entities: https://github.com/james2m/seedbank

2020-12-27 18:41 UTC, vladveterok commented on Gemfile
> +  gem 'database_cleaner-active_record', '~> 1.8'
Good point, thanks!

2020-12-27 18:41 UTC, vladveterok commented on app/controllers/api/v1/comments_controller.rb
> +      end
Fixed.

2020-12-27 18:42 UTC, vladveterok commented on app/models/project.rb
> +end
Done

2020-12-27 18:44 UTC, vladveterok commented on config/routes.rb
> +  post 'refresh', to: 'refresh#create'
Yeah, why not, thanks)

2020-12-27 18:44 UTC, vladveterok commented on db/migrate/20201216202448_create_projects.rb
> +      # t.string :created_by, null: false
Thanks! Done

2020-12-27 18:49 UTC, vladveterok commented on db/seeds.rb
> +project = Project.create(name: 'Seeded project with tasks', user_id: 1)
Yep, had to do it after adding uniqueness validation:) As for seedbank, don't see necessity of this change in the project of this size, still, thanks for a good suggestion!

2020-12-28 10:33 UTC, DaniilYusha approved these changes
Amazing :rocket: :rocket: :rocket:

2021-01-18 12:21 UTC, merged